name: Verify Apache Installation

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  verify-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Verify Apache Installation
        run: |
          curl -I http://54.80.210.159 | grep "HTTP/1.1 200 OK"
