name: Verify Apache Installation

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  verify-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        
      - name: Wait for 100 seconds
        run: sleep 100

      - name: Verify Apache Installation
        run: |
          curl http://$(terraform output -json instance_public_ip | jq -r '.')  | grep "HTTP/1.1 200 OK"
