name: Verify Apache Installation

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  delay_and_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sleep for 2 minutes
        run: sleep 120  # Sleep for 2 minutes

      - name: Verify Apache Installation
        run: |
          INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip)
          echo "Instance Public IP: $INSTANCE_PUBLIC_IP"
          
          # Check if Apache is installed and running
          curl -I http://$INSTANCE_PUBLIC_IP | head -n 10
